language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.3.7
      script:
        - bundle exec danger
    - rvm: 2.3.7
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
